mysite/courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:course_id>", views.detail, name="detail"),
    path("<int:course_id>/rate/", views.rate, name="rate")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('courses/', include('courses.urls')),
    path('admin/', admin.site.urls),
]

mysite/courses/models.py
from django.db import models
from django.contrib.auth.models import User

class Course(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500, null=True, blank=True)
    rating = models.FloatField(default=0)
    vote_count = models.IntegerField(default=0)

    def average_rating(self, new_rating):
        self.rating = (self.rating * self.vote_count + int(new_rating)) / (self.vote_count + 1)
        self.rating = round(self.rating, 2)
        self.vote_count += 1
        self.save()


class Lecture(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)

mysite/courses/views.py
#
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse
from django.contrib.auth import authenticate, login as _login, logout as _logout
from django.contrib.auth.models import User

#
from .models import Lecture, Course


def home(request):
    if request.user.is_authenticated:
        courses = Course.objects.all()
        context = {
            "courses": courses
        }
        return render(request, "courses/home.html", context)
    else:
        return HttpResponseRedirect("courses/login")


def detail(request, course_id):
    if request.user.is_authenticated:
        course = get_object_or_404(Course, pk=course_id)
        return render(request, "courses/detail.html", {"course": course})

    else:
        return HttpResponseRedirect('/courses/login')


def rate(request, course_id):
    if request.user.is_authenticated:
        if request.method == "GET":
            return render(request, "courses/detail.html")
        else:
            course = Course.objects.get(id=course_id)
            new_rating = float(request.POST.get('rate'))
            course.average_rating(new_rating)
            return HttpResponseRedirect("/courses/")
    else:
        return HttpResponseRedirect("courses/login")





def register(request):
    if request.method == "GET":
        return render(request, "courses/register.html", {})
    else:
        try:
            first_name = request.POST["firstname"]
            last_name = request.POST["lastname"]
            email = request.POST["email"]
            age = request.POST["age"]
            password = request.POST["password"]
            repeat_password = request.POST["repeat_password"]
        except:
            return render(request, "courses/register.html", {"error_message": "Missed Field"})

        if password != repeat_password:
            return render(request, "courses/register.html", {"error_message": "Password not match."})

    user = User.objects.create_user(username=email, email=email, password=password)
    user.first_name = first_name
    user.last_name = last_name
    user.save()

    lecture_user = Lecture(user=user, age=age)
    lecture_user.save()
    return HttpResponseRedirect('/courses/login/')


def login(request):
    if request.method == "GET":
        return render(request, 'courses/login.html', {})
    else:
        try:
            email = request.POST["email"]
            password = request.POST["password"]
        except:
            return render(request, "courses/login.html", {"error_message": "Missed Field"})

    user = authenticate(username=email, password=password)
    print("USER", email, password)
    if user:
        _login(request, user)
        return HttpResponseRedirect('/courses/')

    else:
        return render(request, "courses/login.html", {"error_message": "Email or password is incorrect."})


def logout(request):
    _logout(request)
    return HttpResponseRedirect("/courses/login")

mysite/courses/templates/courses/detail.html
<form action="{% url 'courses:rate' course.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ course.title }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <p>{{ course.description }}</p>
        <input type="text" name="rate" id="course.id" value="", placeholder="0 to 10">
    </fieldset>
    <input type="submit" value="Rate">
</form>

mysite/courses/templates/courses/home.html
<h1>Welcome {{user.first_name}} {{ user.last_name}}</h1>

<h2>Courses</h2>
{% if courses %}
    <ul>
    {% for course in courses %}
        <li><a href="{% url 'courses:detail' course.id %}">{{ course.title }} - {{ course.rating }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No courses available.</p>
{% endif %}
<br>
<a href="{% url 'courses:logout' %}">logout</a>

mysite/courses/templates/courses/login.html
<form action="{% url 'courses:login' %}" method="post">
    {% csrf_token %}
    <legend><h1>Login</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <input type="text" name="email" id="email" value="" placeholder="Email">
    <br>
    <input type="password" name="password" id="password" value="" placeholder="Password">
    <br>
    <input type="submit" value="Login">
</form>

mysite/courses/templates/courses/register.html
<form action="{% url 'courses:register' %}" method="post">
    {% csrf_token %}
    <legend><h1>Register</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <input type="text" name="firstname" id="firstname" value="" placeholder="Firstname">
    <br>
    <input type="text" name="lastname" id="lastname" value="" placeholder="Last Name">
    <br>
    <input type="text" name="email" id="email" value="" placeholder="Email">
    <br>
    <input type="text" name="age" id="age" value="" placeholder="Age">
    <br>
    <input type="password" name="password" id="password" value="" placeholder="Password">
    <br>
    <input type="password" name="repeat_password" id="repeat_password" value="" placeholder="Repeat Password">
    <br>
    <input type="submit" value="Register">
</form>